### PR TITLE
Fix missing organizations in filter on donations page

### PR DESCRIPTION
**Pull request by mishra-ankit**
- Add action, saga, reducer and dispatch to get all organizations
image

Note: **Depends on backend change https://github.com/stiftelsen-effekt/effekt-backend/pull/468**

### CODE REVIEW

**Review by fellmirr — APPROVED** [review]
Perfect :+1:

**Comment by fellmirr** [comment]
Ah, although it doesn't like this:

```
src/components/modules/avtalegiro/agreementlist/AvtaleGiroFilter.tsx
  Line 45:9:  'paymentDateRange' is assigned a value but never used  @typescript-eslint/no-unused-vars
 ```

**Comment by mishra-ankit** [comment]
> 

Bit strange, we didn't change this file though. I'll fix the lint error.

**Comment by mishra-ankit** [comment]
Should be good now. 🤞🏽

**Comment by fellmirr** [comment]
Strange indeed!

**Pull request merged**
