### PR TITLE
Donors: Allow editing

### PR DESCRIPTION
**Pull request by xim**
This closes issue #203

@JorgenLjones feel free to see if this looks good?
Screenshot from 2022-08-17 15-26-52
Screenshot from 2022-08-17 15-27-11
Screenshot from 2022-08-17 15-27-25
Screenshot from 2022-08-17 15-31-05

### CODE REVIEW

**Comment by JorgenLjones** [comment]
Looks good! Will the Newsletter and Trash be marked as a checkmark if True?
Also, don't think we should make available editing the registered timestamp. I can't think of ever having the need of doing that and enabling it increases the risk of error or malice.

**Comment by fellmirr** [comment]
@xim Email should be read-only as well for now, probably safest, as we discussed :)

**Comment by xim** [comment]
Screenshot from 2022-08-17 21-57-59
Screenshot from 2022-08-17 21-58-07

Noe slikt

**Comment by herleik** [comment]
Great work! Very helpful for donation editing as well.

**Pull request merged**
